- cmake/Config.cmake.in
> Fix GTSAMconfig.cmake for cmake <3.8

- cython/setup.py.in
Only text based updated. No code functionality change, hence no unit test.
> Updated python package information

- README.md
- package.xml
- Updated README to nicer Markdown.
- Added links to papers for convenience.
- Added code formatting.
- Updated ROS package version.
> README niceness

- gtsam.h
tiny PR, should be quick approve, Mandy :-)
> wrap printErrors

- tests/testDoglegOptimizer.cpp
> Fixed exception type for TBB path

- gtsam/inference/VariableIndex.h
"const" ignored in this return type
> fix minor warning

- CMakeLists.txt
- gtsam/3rdparty/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/borglab/gtsam/112)
> Add cmake flag to include eigen-unsupported module

- timing/timeGaussianFactorGraph.cpp
using cmake options:
cmake -DGTSAM_BUILD_TIMING_ALWAYS=ON ../gtsam
Just fixed the compile error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/borglab/gtsam/147)
> fix compile error in timeGaussianFactorGraph.cpp

- gtsam/3rdparty/CCOLAMD/Source/ccolamd.c
- gtsam/3rdparty/SuiteSparse_config/Makefile
- gtsam/3rdparty/SuiteSparse_config/README.txt
- gtsam/3rdparty/SuiteSparse_config/SuiteSparse_config.c
- gtsam/3rdparty/SuiteSparse_config/SuiteSparse_config.h
- gtsam/3rdparty/SuiteSparse_config/SuiteSparse_config.mk
Replaced CCOLADM and SuiteSparse_config in 3rdparty with folders from suite-sparse-5.4.0, and passed all the unittests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/borglab/gtsam/157)
>         upgrade colamd to suite-sparse-5.4.0

- cython/gtsam/examples/GPSFactorExample.py
- gtsam.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/borglab/gtsam/155)
>         expose GPSFactor in python wrapper, and add example for it

- gtsam/mainpage.dox
I think NonlinearFactor1, NonlinearFactor2, ... is supposed to say NoiseModelFactor1, NoiseModelFactor2, ...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/borglab/gtsam/166)
> Fix doxygen "Creating a new factor"

- gtsam/base/ConcurrentMap.h
Fixes #181
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/borglab/gtsam/186)
> Fix broken 64bit hash in tbb in 32bit builds

- examples/ImuFactorsExample.cpp
Using combined imu preintegration is still hardcoded though.
If there is any interest in not having preprocessor directives, I'll go ahead and make it a parameter to avoid recompilations
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/borglab/gtsam/195)
> Remove ugly preprocessor directives

- CMakeLists.txt
- README.md
- appveyor.yml
- cmake/GtsamBuildTypes.cmake
- gtsam/3rdparty/metis/CMakeLists.txt
- gtsam/geometry/SO3.cpp
- gtsam/geometry/SO3.h
- gtsam/geometry/SO4.cpp
- gtsam/geometry/SO4.h
- gtsam/geometry/SOn.cpp
- gtsam/geometry/SOn.h
- gtsam/inference/LabeledSymbol.cpp
- gtsam/inference/LabeledSymbol.h
- gtsam/inference/Symbol.cpp
- gtsam/inference/Symbol.h
- gtsam/linear/Scatter.h
- gtsam/linear/VectorValues.cpp
- gtsam/linear/VectorValues.h
- gtsam/nonlinear/Values-inl.h
- gtsam_unstable/partition/FindSeparator-inl.h
Complementary CI for MSVC.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/borglab/gtsam/193)
>  Add AppVeyor CI for MSVC

- cython/gtsam/examples/ImuFactorExample2.py
- cython/gtsam/examples/VisualISAM2Example.py
- examples/ISAM2Example_SmartFactor.cpp
- examples/SFMExample.cpp
- examples/SFMExample_SmartFactor.cpp
- examples/SFMExample_SmartFactorPCG.cpp
- examples/SelfCalibrationExample.cpp
- examples/VisualISAM2Example.cpp
- examples/VisualISAMExample.cpp
- matlab/unstable_examples/+imuSimulator/OdometryExample3D.m
- tests/testVisualISAM2.cpp
Issue #205
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/borglab/gtsam/206)
> make code match comments when creating Pose3 noiseModel instances

- .travis.python.sh
- .travis.sh
- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/borglab/gtsam/224)
> Add Python CI

- cython/setup.py.in
For pip to detect proper package for python 2.
@dellaert
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/borglab/gtsam/223)
> Add two required string for version detection

- cmake/GtsamPybindWrap.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/borglab/gtsam/225)
> [WIP] Additional changes to the new wrapper (next will be the CI)

- gtsam.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/borglab/gtsam/232)
> Wrap Rot3 slerp function to allow for rotation interpolation

- gtsam.h
This PR adds the `simpleCamera` function to the wrapper so we can use it in Python/Matlab to decompose a projection matrix to the calibration and pose matrices.
Super simple PR, should take less than a minute to review.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/borglab/gtsam/246)
> Wrap simpleCamera function 

- cython/gtsam_unstable/examples/TimeOfArrivalExample.py
- gtsam_unstable/examples/TimeOfArrivalExample.cpp
- gtsam_unstable/geometry/Event.cpp
- gtsam_unstable/geometry/Event.h
- gtsam_unstable/geometry/tests/testEvent.cpp
- gtsam_unstable/gtsam_unstable.h
- gtsam_unstable/slam/TOAFactor.h
- gtsam_unstable/slam/tests/testTOAFactor.cpp
Modernized old unit test and added two examples (one c++, one python) to estimate the trajectory of a moving target based on "sounds" it emits (think bird).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/borglab/gtsam/252)
> Time of arrival measurements

- CMakeLists.txt
- gtsam/geometry/tests/testEssentialMatrix.cpp
- gtsam/navigation/PreintegrationParams.h
- gtsam/navigation/tests/testImuFactorSerialization.cpp
- gtsam/nonlinear/NonlinearEquality.h
- gtsam/nonlinear/utilities.h
- gtsam_unstable/slam/AHRS.h
Due to
- Eigen alignment.
- Wrapper code being too long.
- Exceptions which weren't reference.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/borglab/gtsam/260)
> Fixed some wrapper warnings

- tests/testNonlinearOptimizer.cpp
Please see the Overleaf document for rationales.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/borglab/gtsam/235)
> Add More Unit Tests for Robust Noise Models

- gtsam/nonlinear/Values.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/borglab/gtsam/281)
> Fixed error in description for update().

- .github/workflows/build-cython.yml
- .github/workflows/build-linux.yml
- .github/workflows/build-macos.yml
- .github/workflows/build-python.yml
- .github/workflows/build-windows.yml
- .github/workflows/build.yml
- .travis.sh
- cython/gtsam/utils/visual_data_generator.py
- gtsam/base/GenericValue.h
- gtsam/navigation/tests/testAHRSFactor.cpp
- gtsam/slam/BetweenFactor.h
- wrap/python/gtsam_py/utils/visual_data_generator.py
Example output and build result:
https://github.com/ProfFan/gtsam/actions
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/borglab/gtsam/259)
> GitHub Actions CI

- package_scripts/prepare_ubuntu_pkgs_for_ppa.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/borglab/gtsam/298)
> Ubuntu PPA packages: disco is obsolete. Add focal.

- examples/SolverComparer.cpp
Resolves #296
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/borglab/gtsam/297)
> fix uninitialized variable Key first_pose

- gtsam_unstable/examples/TimeOfArrivalExample.cpp
Resolves #294
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/borglab/gtsam/295)
> fix sign-compare warning b/t size_t and int

- wrap/python/gtsam_py/examples/SFMExample.py
- wrap/python/gtsam_py/examples/SFMdata.py
- wrap/python/gtsam_py/utils/plot.py
This PR adds new plotting capabilities to the new PyBind11 based python wrapper. It mirrors the plotting functionality from the cython wrapper.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/borglab/gtsam/293)
> Plotting for new python wrapper

- gtsam/CMakeLists.txt
- gtsam/base/GenericValue.h
- gtsam/base/types.cpp
- gtsam/base/types.h
- gtsam/nonlinear/Values.cpp
- gtsam/nonlinear/internal/ExpressionNode.h
- gtsam/nonlinear/tests/testValues.cpp
This PR fixes #311.
I expect to get quite a bit of feedback regarding this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/borglab/gtsam/313)
> Demangle the type when printing

- gtsam/linear/Preconditioner.cpp
- gtsam/nonlinear/NonlinearOptimizer.cpp
- tests/testNonlinearOptimizer.cpp
- tests/testPCGSolver.cpp
#	gtsam/nonlinear/NonlinearOptimizer.cpp
#	tests/testPCGSolver.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/borglab/gtsam/318)
> Formatting only

- gtsam/navigation/PreintegrationBase.cpp
Speed up of `predict` in `PreintegrationBase.cpp` by asking for jacobians for `predict_state` and `predict_delta` optionally.
Also removed the TODO since `testIMUFactor.cpp` has tests for correctness.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/borglab/gtsam/323)
> Optional jacobian computation in PreintegrationBase predict function

- gtsam/linear/GaussianFactor.cpp
That is... :-)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/borglab/gtsam/339)
> remove out-of-place pragma

- cython/gtsam/utils/plot.py
- Fixed plotting functions
- Renamed `P` to more descriptive `covariance`
- Added docstrings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/borglab/gtsam/341)
> Plotting updates

- gtsam/base/types.h
I cherry-picked this from the pybind wrapper PR. Hopefully this works...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/borglab/gtsam/375)
> Fix MSVC Build in AppVeyor

- gtsam/base/types.h
Fix MSVC Build in AppVeyor v2.0
cc #375
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/borglab/gtsam/376)
> Fix missing DLL exported symbol

- gtsam/geometry/SOn.h
Answers #383 (the include is not, in fact necessary; @ProfFan , you might want to check `feature/new_wrapper` to see if it is needed there either)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/borglab/gtsam/384)
> Unnecessary include statement

- examples/IMUKittiExampleGPS.cpp
Tested, compared and verified against MATLAB results.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/borglab/gtsam/249)
> Added ported C++ version of ISAM2 Kitti example

- gtsam/navigation/CombinedImuFactor.cpp
- gtsam/navigation/CombinedImuFactor.h
- gtsam/navigation/tests/testImuFactorSerialization.cpp
> Move the boost serialization declaration of CombinedImuFactor to cpp file

- CMakeLists.txt
Simple indent, no code changes.
> Correct indentation for Python version

- gtsam/nonlinear/AdaptAutoDiff.h
Resolves #410 
Just a simple fix.
> set default initialization

- GTSAM-Concepts.md
- gtsam/geometry/Pose3.cpp
- gtsam/geometry/Pose3.h
- gtsam/geometry/tests/testPose3.cpp
Re-opening issue  #415 and fixing it, at least in Pose3 for now.
> Fixed conventions for Jacobians

- gtsam/navigation/TangentPreintegration.cpp
Just some minor comments to make the code easier to understand for those who come later.
No code changes.
> Added more comments for clearer understanding

- gtsam/nonlinear/FunctorizedFactor.h
just a warning fix in the functorized factor
> remove unused base variable

- examples/SolverComparer.cpp
- gtsam/geometry/SO4.cpp
- gtsam/geometry/SO4.h
- timing/timeFactorOverhead.cpp
- timing/timeFrobeniusFactor.cpp
- timing/timeMatrixOps.cpp
follow up in spirit to #233 
this pr removes all boost random
> replace boost random with std random

- cmake/GtsamBuildTypes.cmake
- gtsam/base/timing.cpp
- gtsam/discrete/DecisionTreeFactor.cpp
- gtsam/discrete/DiscreteBayesTree.h
- gtsam/discrete/Potentials.cpp
- gtsam/linear/GaussianBayesTree.h
- gtsam/linear/Preconditioner.cpp
- gtsam/linear/VectorValues.cpp
- gtsam/nonlinear/ISAM2Clique.h
- gtsam/slam/dataset.cpp
- gtsam/symbolic/SymbolicBayesTree.h
- wrap/Module.cpp
> Fix clang warnings

- gtsam/base/GenericValue.h
- gtsam/nonlinear/Values.cpp
- gtsam/nonlinear/Values.h
- gtsam/nonlinear/tests/testValues.cpp
Add: 
- Constructor from `initializer_list`
- `genericValue()` helper macro for the new constructor.
- Unit tests.
> Add C++11 brace initializer_list to Values

- python/CMakeLists.txt
- python/gtsam_py/gtsam.tpl
- python/gtsam_py/python/__init__.py
- python/setup.py.in
1. Fixed the `python-install` make command.
2. Updated the `__init__.py` file to have a common numpy import.
3. Cleaned up the `setup.py` a bit.
4.  ~~Updated the cpp template to include the stl.h header so KeyVector works~~
> Minor updates to the pybind wrapper

- gtsam/nonlinear/ExpressionFactor.h
- gtsam/sam/BearingFactor.h
- gtsam/sam/BearingRangeFactor.h
- gtsam/sam/RangeFactor.h
- gtsam/sam/tests/testBearingFactor.cpp
- gtsam/sam/tests/testBearingRangeFactor.cpp
- gtsam/sam/tests/testRangeFactor.cpp
- tests/testExpressionFactor.cpp
* Add variadic-template N-ary ExpressionFactor
* Deprecate ExpressionFactor2
* More unit tests for RangeFactor
* Closes #443
> Add N-ary template expression factors

- .travis.yml
- gtsam/slam/FrobeniusFactor.h
This is the reason the Windows build is breaking on Appveyor.
> Fix FrobeniusBetweenFactor declaration

- README.md
- python/setup.py.in
Otherwise pypi will not allow the wheel to be uploaded.
> Make sure our readme is proper restructuredText

- gtsam/gtsam.i
Fixes regression introduced in #532.
> Remove logmap function from LieVector and LieMatrix

- python/gtsam/examples/ImuFactorExample.py
Small fixes to ensure marginals are computed correctly and example doesn't throw issues.
> ImuFactorExample minor fixes

- wrap/matlab_wrapper.py
Updated wrap to include fixes for multiple template parameters.
> Wrap update

- gtsam/geometry/tests/testSerializationGeometry.cpp
- python/gtsam/tests/test_Pose3.py
- wrap/pybind_wrapper.py
- wrap/tests/expected-python/geometry_pybind.cpp
> Fix Python serialization

- .github/workflows/build-linux.yml
- .github/workflows/build-python.yml
> Fix inteminent sks keyserver failure

- cmake/HandlePython.cmake
> Fix python discovery for MATLAB wrapper

- gtsam/geometry/Cal3.h
- gtsam/geometry/Cal3Bundler.cpp
- gtsam/geometry/Cal3Bundler.h
- gtsam/geometry/Cal3DS2.h
- gtsam/geometry/Cal3DS2_Base.cpp
- gtsam/geometry/Cal3DS2_Base.h
- gtsam/geometry/Cal3Fisheye.cpp
- gtsam/geometry/Cal3Fisheye.h
- gtsam/geometry/Cal3Unified.cpp
- gtsam/geometry/Cal3Unified.h
- gtsam/geometry/SimpleCamera.h
- gtsam/geometry/tests/testCal3DFisheye.cpp
- gtsam/geometry/tests/testCal3DS2.cpp
- gtsam/geometry/tests/testCal3Unified.cpp
- gtsam/gtsam.i
- gtsam_unstable/slam/serialization.cpp
- tests/testSerializationSLAM.cpp
- Add jacobians for calibrate function of Cal3DS2 based models using implicit function theorem.
- Consistent naming of jacobian parameters.
- Added tests for jacobians.
- Some simple formatting.
- Fixed docs for implicit function theorem.
- Added parentheses to conform with Google style.
Fixes #621
> Jacobians for Camera models

- gtsam/geometry/Cal3_S2.cpp
- gtsam/geometry/Cal3_S2Stereo.cpp
- gtsam/geometry/Cal3_S2Stereo.h
- gtsam/geometry/tests/testCal3_S2Stereo.cpp
Added methods and tests for `calibrate` and `uncalibrate` in `Cal3_S2Stereo`.
> Cal3_S2Stereo Calibrate and Uncalibrate 

- cmake/GtsamTesting.cmake
The formatting in the `GtsamTesting.cmake` file was off, so just fixed it.
> Minor formatting

- .github/scripts/python.sh
- .github/workflows/build-python.yml
- python/CMakeLists.txt
- python/MANIFEST.in
- python/setup.py.in
> Add dataset directly to package

- gtsam/gtsam.i
- gtsam_unstable/slam/SmartStereoProjectionPoseFactor.h
A bunch of miscellaneous fixes to remove warnings and provide more functionality.
> Miscellaneous fixes

- .github/workflows/build-python.yml
- Fan's version of `homebrew`'s `boost` is out of date.
> Use brew's boost, instead of Fan's version

- gtsam/gtsam.i
1. Added double as a template for `PriorFactor`
2. NavState retract and local
3. Some formatting
> Double + NavState in the wrapper

- gtsam/navigation/ImuFactor.cpp
- gtsam/navigation/ImuFactor.h
- gtsam/nonlinear/GncOptimizer.h
> Bunch of minor fixes

- examples/CombinedImuFactorsExample.cpp
- examples/ImuFactorsExample.cpp
> Correct ImuFactorExamples frame description

- gtsam/slam/expressions.h
- tests/testExpressionFactor.cpp
Add `cross()` and `dot()` as expressions. Added the corresponding unit tests.
> add expressions for cross() and dot()

- .github/workflows/build-linux.yml
- .github/workflows/build-python.yml
- .github/workflows/build-special.yml
This should fix the build issue for the Linux CI.
> Update the pgp servers to get the LLVM GPG key

- gtsam/slam/tests/testBetweenFactor.cpp
Added lots of tests which were missing, as well as uncommented existing tests so we have more confidence in this factor.
> Tests for BetweenFactor

- gtsam/geometry/PinholeCamera.h
- gtsam/geometry/PinholePose.h
> Add Windows export symbols for PinholeCamera

- python/gtsam/examples/SFMdata.py
> clean up SFMdata python module

- gtsam/inference/Key.h
- gtsam/linear/linear.i
- gtsam/nonlinear/nonlinear.i
- python/gtsam/gtsam.tpl
Did some wrapping in order to be able to do some elimination on the state estimator. Should be useful going forward for others.
> Jacobian Factor Wrapping

- .github/scripts/unix.sh
I made an error when improving the performance of the CI due to which the tests were not being run. This PR fixes it.
> Run tests for C++ CI

- gtsam/nonlinear/Expression-inl.h
- gtsam/nonlinear/tests/testExpression.cpp
Enable * operator for double expressions
> enable expression double multiply

- gtsam/linear/GaussianFactorGraph.cpp
- gtsam/linear/GaussianFactorGraph.h
- gtsam/linear/linear.i
Added this as I was debugging stuff in MHS.
> Add printErrors method to GaussianFactorGraph

- examples/FisheyeExample.cpp
- examples/Pose2SLAMExample_graphviz.cpp
> Use non-deprecated graphviz methods

- gtsam/hybrid/DCMixtureFactor.h
As I was constructing an example, I felt the need for printing. It works in a different branch.
I also removed gtsam:: scope as I thought #972 was merged, but I see it is not yet...
> print DCMixtureFactor

- python/gtsam_unstable/gtsam_unstable.tpl
- wrap/cmake/PybindWrap.cmake
- wrap/gtwrap/pybind_wrapper.py
- wrap/scripts/pybind_wrap.py
This PR adds the latest wrapper update which supports individual module compilation.
@dellaert can you please use this branch and see if it works well for you?
> Wrapper Update

- gtsam/hybrid/DCGaussianMixtureFactor.h
- gtsam/hybrid/HybridFactorGraph.cpp
- gtsam/hybrid/HybridFactorGraph.h
- gtsam/hybrid/tests/testDCGaussianElimination.cpp
- gtsam/hybrid/tests/testHybridFactorGraph.cpp
emplace variants, automatically deduce the right graph.
Unfortunately emplace variants don't deal well with {}, but it works with auto.
> HybridFactorGraph emplace variants

- gtsam/discrete/DiscreteConditional.cpp
- gtsam/discrete/discrete.i
- gtsam/discrete/tests/testDiscreteBayesNet.cpp
- gtsam/inference/DotWriter.h
- gtsam/inference/FactorGraph-inst.h
- gtsam/inference/FactorGraph.h
- gtsam/nonlinear/NonlinearFactorGraph.cpp
- gtsam/nonlinear/NonlinearFactorGraph.h
- gtsam/nonlinear/nonlinear.i
Sorry for the churn, but I screwed up argument order in factor graph `dot` methods.
I switched formatter and writer arguments to be more inline with BayesNet etc.
> dot argument order

- examples/UGM_small.cpp
- gtsam/nonlinear/NonlinearFactorGraph.h
Two examples did not compile. Don't know why CI did not catch this before.
> Two small fixes

- gtsam/hybrid/HybridFactorGraph.cpp
- gtsam/hybrid/HybridFactorGraph.h
This PR fixes the Windows build on the CI.
> Fix Windows build for Hybrid Factor Graph

- gtsam/slam/slam.i
- python/gtsam/tests/test_BetweenFactor.py
Wrapped double so we can run tests in Python as well for quick and easy examination.
> Wrap double for between factor

- gtsam/discrete/DecisionTree.h
- gtsam/discrete/tests/testDecisionTree.cpp
> Unzip for DecisionTree

- gtsam/hybrid/HybridFactorGraph.cpp
- gtsam/hybrid/HybridFactorGraph.h
- gtsam/hybrid/tests/testHybridFactorGraph.cpp
- gtsam/linear/HessianFactor.cpp
> Minor improvements to DC related stuff

- gtsam/discrete/DiscreteFactorGraph.cpp
- gtsam/discrete/DiscreteFactorGraph.h
- gtsam/discrete/discrete.i
- gtsam/discrete/tests/testDiscreteFactorGraph.cpp
- gtsam/nonlinear/nonlinear.i
- python/gtsam/tests/test_DiscreteFactorGraph.py
> Added sumProduct as a convenient alias

- gtsam/nonlinear/nonlinear.i
As the title says. This should solve your issues, @dellaert.
> Wrap ParameterMatrix as argument for Values

- gtsam/geometry/geometry.i
- gtsam/geometry/triangulation.h
- gtsam/linear/SubgraphBuilder.cpp
- python/gtsam/specializations/geometry.h
- python/gtsam/tests/test_Triangulation.py
Wrap the more sophisticated triangulation code from triangulation.h.
I also slightly modified the `TriangulationResult` class.
> Wrap triangulateSafe

- gtsam/geometry/Rot3.cpp
> fix typo issue in comment

- .github/workflows/build-macos.yml
- .github/workflows/build-python.yml
- python/CMakeLists.txt
macos 10.15 has been deprecated so this PR updates the CI to use macos 11.
> Update macos CI env

- gtsam/hybrid/tests/testHybridBayesNet.cpp
> Switch pruning test to probabilities

- gtsam/hybrid/tests/testHybridBayesNet.cpp
@varunagrawal because this was merged after the split, we also need to merge in release/4.2
> Switch pruning test to probabilities.

- gtsam/geometry/CameraSet.h
- gtsam/slam/SmartFactorBase.h
fix fix ambiguous template variadic variable issue on non-gcc compilers https://stackoverflow.com/questions/56943558/c-partial-template-argument-deduction-for-function-with-variadic-pack-produces
> fix ambiguous template variadic variable issue

- package.xml
> Patch ros package (branch: release/4.2)

- python/gtsam/preamble/inference.h
Somehow in some unrelated PR all these includes were removed. Trying to add this one back to see whether it fixes issue in gtbook.
> Add missing header to fix gtbook

- package.xml
> Update ROS package.xml format to v3 and update gtsam version (develop branch)

- package.xml
cc: https://github.com/ros/rosdistro/pull/35980
> More details on source licenses

- CppUnitLite/Test.cpp
- CppUnitLite/Test.h
- cmake/example_cmake_find_gtsam/CMakeLists.txt
- cmake/obsolete/GtsamTestingObsolete.cmake
- gtsam/slam/tests/testLago.cpp
Also made some CMake updates and fixed some warnings.
> Update CppUnitLite to not rely on boost

- gtsam/hybrid/HybridGaussianFactorGraph.cpp
- gtsam/hybrid/HybridNonlinearFactorGraph.cpp
- gtsam/hybrid/HybridSmoother.cpp
- gtsam/hybrid/HybridSmoother.h
- gtsam/hybrid/tests/testGaussianMixtureFactor.cpp
- gtsam/hybrid/tests/testHybridGaussianFactorGraph.cpp
Added support for additional factor and conditional types in hybrid factors.
> Better Hybrid support

- gtsam/base/timing.cpp
- gtsam/hybrid/HybridGaussianFactorGraph.cpp
- gtsam/hybrid/HybridSmoother.cpp
- gtsam/hybrid/HybridSmoother.h
- gtsam/hybrid/tests/testHybridEstimation.cpp
- gtsam/navigation/ConstantVelocityFactor.h
- gtsam/navigation/ManifoldPreintegration.cpp
- gtsam/navigation/ManifoldPreintegration.h
- gtsam/navigation/TangentPreintegration.cpp
1. Fix typos
2. Remove duplicate `getOrdering` function.
3. Fix `HYBRID_TIMING` calls to allow outer scoop timing.
4. Update `HybridSmoother` to follow the same pattern as `HybridISAM`.
> Various Fixes and Updates

- gtsam/geometry/geometry.i
Exposing Jacobians for some Unit3 methods.
> Wrap Unit3 methods with Jacobians

- gtsam/geometry/geometry.i
- matlab/gtsam_tests/testCal3Unified.m
I introduced a bug in the Matlab wrapper when wrapping code in #1524.
This PR fixes it and adds an additional matlab test.
> Fix geometry wrapper

- gtsam/base/treeTraversal-inst.h
- gtsam/linear/LossFunctions.h
Fixed some doxygen rendering issues a while ago. Closing it out.
> Fix doxygen issues

- gtsam/sfm/ShonanAveraging.cpp
- gtsam/sfm/tests/testShonanAveraging.cpp
- python/gtsam/tests/test_ShonanAveraging.py
- in response to GTSAM group question
- also added a check on pMin, which segfaulted if pMin < d :-(
> Added some python and c++ examples with BinaryMeasurements

- gtsam/geometry/tests/testRot3.cpp
Add a test to debug issue #1588
One can never have too many tests :-)
> Additional quaternion test

- .github/workflows/build-windows.yml
- CMakeLists.txt
- gtsam/basis/Basis.h
- gtsam/discrete/SignatureParser.h
- gtsam/geometry/Line3.h
- gtsam/geometry/Pose2.h
- gtsam/geometry/Pose3.h
- gtsam/hybrid/HybridFactorGraph.h
- gtsam/hybrid/HybridSmoother.h
- gtsam/hybrid/tests/testHybridGaussianFactorGraph.cpp
- gtsam/inference/Ordering.h
- gtsam_unstable/linear/LPInitSolver.h
- gtsam_unstable/linear/QPSParser.h
Fix #1541
Minimum changes for fix windows tests.
This PR is aiming to fix compilation errors. 
Although it not fix all the compilation errors, it solve the majority of them. 
@dellaert Can you take a look of this?
> Fix windows tests

- .github/scripts/python.sh
- .github/scripts/unix.sh
- .github/workflows/build-linux.yml
- .github/workflows/build-python.yml
- .github/workflows/build-special.yml
- .github/workflows/build-windows.yml
> Add ninja build
